
# Syntax highlighting
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           /:title

# Setup
timezone:            Asia/Shanghai # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				         WILL CHANGE
title:               will's blog
tagline:             'Product Designer'
description:         'I'm a Product Designer'
url:                 http://willchange.cn
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 xiaowei chang
  url:            	 http://willchange.cn
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          pujian
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"

# Plugins
plugins: [jekyll-paginate]
